import type { Metadata } from "next";
import { Geist, Geist_Mono, Alex_Brush, Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { KindeProvider } from "@kinde-oss/kinde-auth-nextjs";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { CartProvider } from "@/app/components/CartContext";
import ScrollNavbar from "@/app/components/ScrollNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alexBrush = Alex_Brush({
  subsets: ["latin"],
  weight: "400",
});

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const { isAuthenticated, getUser } = getKindeServerSession();

  const authenticated = Boolean(await isAuthenticated());
  const user = await getUser();
  console.log(user)
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <KindeProvider>
          <CartProvider>
            <ScrollNavbar
              authenticated={authenticated}
              user={user}
              alexBrushClass={alexBrush.className}
              josefinSansClass={josefinSans.className}
              poppinsClass={poppins.className}
            />
            {children}
          </CartProvider>
        </KindeProvider>
      </body>
    </html>
  );
}