import type { Metadata } from "next";
import { Geist, Geist_Mono, Alex_Brush, Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { RegisterLink, LoginLink, KindeProvider } from "@kinde-oss/kinde-auth-nextjs";
import Link from "next/link";
import { LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import CartBadge from "@/app/components/CartBadge";
import { CartProvider } from "@/app/components/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alexBrush = Alex_Brush({
  subsets: ["latin"],
  weight: "400",
});

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const { isAuthenticated, getUser } = getKindeServerSession();

  const authenticated = Boolean(await isAuthenticated());
  const user = await getUser();
  console.log(user)
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <KindeProvider>
          <CartProvider>
            {/* ── Professional Navbar ── */}
            <nav className="sticky top-0 z-50 bg-slate-950 border-b border-slate-800 shadow-lg shadow-slate-950/20">
            <div className="max-w-7xl mx-auto px-6 py-3 flex flex-wrap items-center justify-between gap-4">

              {/* Brand */}
              <Link href="/" className="flex flex-col leading-tight">
                <span className={`text-3xl text-slate-100 leading-none ${alexBrush.className}`}>Payal Fabric</span>
                <span className={`text-[10px] text-slate-400 tracking-[0.2em] uppercase ${josefinSans.className}`}>Only For Ladies</span>
              </Link>

              {/* Nav Links */}
              <ul className={`flex flex-wrap items-center gap-5 text-sm font-medium text-slate-300 ${poppins.className}`}>
            <li>
              <Link href="/" className="relative hover:text-purple-200 transition-colors duration-200 after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-[2px] after:bg-purple-400 after:transition-all after:duration-300 hover:after:w-full">Home</Link>
            </li>
            <li>
              <Link href="/women" className="relative hover:text-purple-200 transition-colors duration-200 after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-[2px] after:bg-purple-400 after:transition-all after:duration-300 hover:after:w-full">Women&apos;s Wear</Link>
            </li>
            <li>
              <Link href="/fabrics" className="relative hover:text-purple-200 transition-colors duration-200 after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-[2px] after:bg-purple-400 after:transition-all after:duration-300 hover:after:w-full">Fabrics</Link>
            </li>
            <li>
              <Link href="/accessories" className="relative hover:text-purple-200 transition-colors duration-200 after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-[2px] after:bg-purple-400 after:transition-all after:duration-300 hover:after:w-full">Accessories</Link>
            </li>
            <li>
              <Link href="/contact" className="relative hover:text-purple-200 transition-colors duration-200 after:absolute after:-bottom-1 after:left-0 after:w-0 after:h-[2px] after:bg-purple-400 after:transition-all after:duration-300 hover:after:w-full">Contact</Link>
            </li>
            <li>
              <CartBadge />
            </li>

            {!authenticated ? (
              <>
                <li>
                  <RegisterLink className="px-4 py-1.5 rounded-full border border-purple-500 text-purple-200 hover:bg-purple-950/30 transition-colors duration-200 text-sm font-medium">Register</RegisterLink>
                </li>
                <li>
                  <LoginLink className="px-4 py-1.5 rounded-full bg-purple-600 text-white hover:bg-purple-500 transition-colors duration-200 text-sm font-medium">Login</LoginLink>
                </li>
              </>
            ) : (
              <>
                <li className="text-purple-200 font-semibold">{user?.given_name}</li>
                <li>
                  <LogoutLink className="px-4 py-1.5 rounded-full border border-purple-500 text-purple-200 hover:bg-purple-950/30 transition-colors duration-200 text-sm font-medium">Logout</LogoutLink>
                </li>
              </>
            )}

          </ul>
        </div>
      </nav>
          {children}
          </CartProvider>
        </KindeProvider>
      </body>
    </html>
  );
}