-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "Color" DROP DEFAULT,
ALTER COLUMN "FabricType" DROP DEFAULT,
ALTER COLUMN "MainCategory" DROP DEFAULT,
ALTER COLUMN "Material" DROP DEFAULT,
ALTER COLUMN "SubCategory" DROP DEFAULT;
